### ISSUE TITLE
Provision drops to 1

### ISSUE THREAD

**Issue by ghost** [channl/dynamodb-lambda-autoscale#1]
Thank you for this excellent project!

I have only one big issue when i use this package:
![image](https://cloud.githubusercontent.com/assets/57482/15046211/431d1260-12e7-11e6-97c3-97bafdc6e208.png)

Do you have any idea how I can get around this issue? 

Thanks!

**Comment by tmitchel2** [comment]
Hi Felix,

Thanks for trying it out.  The rapid drop is actually done on purpose because AWS only allows 4 decrements per calendar day but as many increments as you like, so given that it's normally much better to drop right down and pick up again if needed.

From your chart it looks like its adjusting the provisioned capacity exactly right in response to the consumed capacity.

However, if you did really want to change the behaviour then you simply need to adjust you logic in https://github.com/channl/dynamodb-lambda-autoscale/blob/master/src/Config.js in the decrement. calculateValue functions.

Hope that explains it?
