### ISSUE TITLE
Is there a setting to limit the number of downscales per day?

### ISSUE THREAD

**Issue by chriskinsman** [channl/dynamodb-lambda-autoscale#48]
I see a constant in RateLimitedDecrement.js that I could change from 4 to the desired value I suspect but wasn't sure if this could be done via config.

Since we have to fork to deploy anyway I can just change the constant.

We have a challenge where we scale reads way up on a table, dump to S3, and then scale them back down.  We need to reserve at least one decrement window in the 24 hour window for this process.  Reducing the 4 to a 3 seems like it will solve this need.

Thanks!

**Comment by tmitchel2** [comment]
Hmmm, the number of downscales per calendar day is limited to 4 by AWS and I take that into account.  The logic i apply is to split the remaining portion of the calendar day into sections so that downscales only become available on incremental basis (it's a little bit less naive than just chopping the 24hr period into 4 sections).  I myself run tasks that scale reads way up and then drop right back to 1, I've found the logic so far works quite well for me as is.

I would suggest running it / testing it as is and if it doesn't quite work as you expect then attach the resultant chart from aws console ui and we can go from there...
