### ISSUE TITLE
Configuration per table group

### ISSUE THREAD

**Issue by chriskinsman** [channl/dynamodb-lambda-autoscale#49]
I have multiple groups of tables each of which need a different set of configuration settings.

These tables all have similar stems.  Is the best way to do this by modifying Provisioner.js to look for those specific tables and load configs for each?

**Comment by tmitchel2** [comment]
Yes exactly, you need to modify getTableConfig method.  Can I ask why you need different profiles / configuration?  Not that it's wrong, just that I would like to make it work for all cases with a single config and most likely a max value...

**Comment by chriskinsman** [comment]
The biggest one is min/max for each grouping of tables.  The only other issue is whether it should be read, write or both.

**Comment by tmitchel2** [comment]
So for min I think 1 is adequate because obviously lower is better in terms of cost and the provisioner will never provision less than you need (unless you change the default settings.  Potentially a massive spike and throttles could be avoided but I've included functionality to cover most of those cases also.  Please let me know if you think of a scenario that I missed..

For max yes I can see that definitely as being a requirement but you could either just lump it and put a high number across the board to keep things simple (it's not going to use it just because it's able to) or maybe use the default config as a prototype, clone it and then just modify the max values using a map of table name to max value..?

**Comment by chriskinsman** [comment]
Realized the groupings also have different scale characteristics in terms of how quickly they ramp up and/or down.  Just going with multiple files for now I think.
